name: Build TweakLoader

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        uses: actions-cool/theos-action@v1

      - name: Build
        run: |
          cd TweakLoader
          make package FINALPACKAGE=1
        env:
          THEOS: /opt/theos

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TweakLoader-deb
          path: TweakLoader/*.deb
